static const TCHAR *NpHvkMaterialNames[] =
{
	TEXT("Stone"),
	TEXT("Cloth"),
	TEXT("Dirt"),
	TEXT("Glass"),
	TEXT("Grass"),
	TEXT("Metal"),
	TEXT("Organic"),
	TEXT("Skin"),
	TEXT("Water"),
	TEXT("Wood"),
	TEXT("Heavy Stone"),
	TEXT("Heavy Metal"),
	TEXT("Heavy Wood"),
	TEXT("Chain"),
	TEXT("Snow"),
	TEXT("Stone Stairs"),
	TEXT("Cloth Stairs"),
	TEXT("Dirt Stairs"),
	TEXT("Glass Stairs"),
	TEXT("Grass Stairs"),
	TEXT("Metal Stairs"),
	TEXT("Organic Stairs"),
	TEXT("Skin Stairs"),
	TEXT("Water Stairs"),
	TEXT("Wood Stairs"),
	TEXT("Heavy Stone Stairs"),
	TEXT("Heavy Metal Stairs"),
	TEXT("Heavy Wood Stairs"),
	TEXT("Chain Stairs"),
	TEXT("Snow Stairs"),
	TEXT("Elevator"),
	NULL
};

static const TCHAR *NpHvkLayerNames[] =
{
	TEXT("Unidentified"),
	TEXT("Static"),
	TEXT("AnimStatic"),
	TEXT("Transparent"),
	TEXT("Clutter"),
	TEXT("Weapon"),
	TEXT("Projectile"),
	TEXT("Spell"),
	TEXT("Biped"),
	TEXT("Tree"),
	TEXT("Prop"),
	TEXT("Water"),
	TEXT("Trigger"),
	TEXT("Terrain"),
	TEXT("Trap"),
	TEXT("NonCollidable"),
	TEXT("CloudTrap"),
	TEXT("Ground"),
	TEXT("Portal"),
	TEXT("Stairs"),
	TEXT("CharController"),
	TEXT("AvoidBox"),
	TEXT("?"),
	TEXT("?"),
	TEXT("CameraPick"),
	TEXT("ItemPick"),
	TEXT("LineOfSight"),
	TEXT("PathPick"),
	TEXT("CustomPick1"),
	TEXT("CustomPick2"),
	TEXT("SpellExplosion"),
	TEXT("DroppingPick"),
	TEXT("Other"),
	TEXT("Head"),
	TEXT("Body"),
	TEXT("Spine1"),
	TEXT("Spine2"),
	TEXT("LUpperArm"),
	TEXT("LForeArm"),
	TEXT("LHand"),
	TEXT("LThigh"),
	TEXT("LCalf"),
	TEXT("LFoot"),
	TEXT("RUpperArm"),
	TEXT("RForeArm"),
	TEXT("RHand"),
	TEXT("RThigh"),
	TEXT("RCalf"),
	TEXT("RFoot"),
	TEXT("Tail"),
	TEXT("SideWeapon"),
	TEXT("Shield"),
	TEXT("Quiver"),
	TEXT("BackWeapon"),
	TEXT("BackWeapon"),
	TEXT("PonyTail"),
	TEXT("Wing"),
	NULL
};

static const TCHAR *NpHvkMotionSystems[] =
{
	TEXT("0: Invalid"),
	TEXT("1: Dynamic"),
	TEXT("2: Sphere"),
	TEXT("3: Sphere Inertia"),
	TEXT("4: Box"),
	TEXT("5: Box Stabilized"),
	TEXT("6: Keyframed"),
	TEXT("7: Fixed"),
	TEXT("8: Thin Box"),
	TEXT("9: Character"),
	NULL
};

static const TCHAR *NpHvkQualityTypes[] =
{
	TEXT("0: Invalid"),
	TEXT("1: Fixed"),
	TEXT("2: Keyframed"),
	TEXT("3: Debris"),
	TEXT("4: Moving")
	TEXT("5: Critical"),
	TEXT("6: Bullet"),
	TEXT("7: User"),
	TEXT("8: Character"),
	TEXT("9: Keyframed Report"),
	NULL
};
